apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-react-app
  template:
    metadata:
      labels:
        app: todo-react-app
    spec:
      containers:
      - name: todo-react-app
        image: schoudhary94/todo-react-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-react-service
spec:
  type: NodePort
  selector:
    app: todo-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
